### ISSUE TITLE
go mod tidy is complaining

### ISSUE THREAD

**Issue by philhug** [jwkohnen/airac#3]
```
user@unknown:~/gocode/src/github.com/jwkohnen/airac$ go mod tidy
go: finding github.com/jwkohnen/airac/proto latest
github.com/jwkohnen/airac imports
	github.com/jwkohnen/airac/proto: no matching versions for query "latest"
```
I see 2 possible workarounds: commit the `airac.pb.go` file or add a dummy .go file into the proto directory with the content `package proto`

**Comment by jwkohnen** [comment]
Hello Philipp, good catch, thank you. Indeed I had that dummy file lying around locally. I'd prefer that workaround because it also removes the protobuf dependency. I guess it's better for downstream packages to deal with that dependency, and maybe it is a bad idea to have this proto checked in anyway.
